# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-26 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=40)),
                ('lastName', models.CharField(max_length=40)),
                ('email', models.EmailField(blank=True, max_length=200)),
                ('passwd', models.CharField(max_length=80)),
            ],
        ),
    ]
