# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-26 05:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackEvent', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='passwd',
            new_name='user_asswd',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='email',
            new_name='user_email',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='firstName',
            new_name='user_fname',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='lastName',
            new_name='user_lname',
        ),
    ]
