# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-26 05:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackEvent', '0002_auto_20161126_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='user_asswd',
            new_name='user_passwd',
        ),
    ]
