# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-26 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackEvent', '0003_auto_20161126_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=40)),
                ('event_desc', models.CharField(max_length=40)),
                ('event_venue', models.CharField(max_length=80)),
            ],
        ),
    ]
